Revert "[TODO revert] test"
This reverts commit 0abc3d52006a8d5f8a9265cbc975bbcf85b8cd14.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,39 +3,39 @@ on:
   pull_request:
 
 jobs:
-#  test-lint:
-#    name: runner / sqlfluff (github-check)
-#    runs-on: ubuntu-latest
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        sqlfluff: ["0.9.4", "0.10.1", "0.11.1"]
-#    steps:
-#      - uses: actions/checkout@v2
-#      - uses: ./
-#        id: lint-sql
-#        with:
-#          github_token: ${{ secrets.github_token }}
-#          reporter: github-check
-#          sqlfluff_version: ${{ matrix.sqlfluff }}
-#          sqlfluff_command: lint
-#          templater: jinja
-#          config: "${{ github.workspace }}/testdata/test_failed_dbt/.sqlfluff"
-#          paths: '${{ github.workspace }}/testdata/test_failed_dbt/models'
-#      - name: check the exit code
-#        if: ${{ !success() }}
-#        run: echo 'The previous step should fail' && exit 1
-#      - name: "Test outputs"
-#        if: always()
-#        shell: bash
-#        run: |
-#          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
-#          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
-#          echo '${{ steps.lint-sql.outputs.sqlfluff-exit-code }}'
-#          echo '${{ steps.lint-sql.outputs.reviewdog-exit-code }}'
+  test-lint:
+    name: runner / sqlfluff (github-check)
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        sqlfluff: ["0.9.4", "0.10.1", "0.11.1"]
+    steps:
+      - uses: actions/checkout@v2
+      - uses: ./
+        id: lint-sql
+        with:
+          github_token: ${{ secrets.github_token }}
+          reporter: github-check
+          sqlfluff_version: ${{ matrix.sqlfluff }}
+          sqlfluff_command: lint
+          templater: jinja
+          config: "${{ github.workspace }}/testdata/test_failed_dbt/.sqlfluff"
+          paths: '${{ github.workspace }}/testdata/test_failed_dbt/models'
+      - name: check the exit code
+        if: ${{ !success() }}
+        run: echo 'The previous step should fail' && exit 1
+      - name: "Test outputs"
+        if: always()
+        shell: bash
+        run: |
+          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
+          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
+          echo '${{ steps.lint-sql.outputs.sqlfluff-exit-code }}'
+          echo '${{ steps.lint-sql.outputs.reviewdog-exit-code }}'
 
   test-fix:
-#    needs: ["test-lint"]
+    needs: ["test-lint"]
     name: runner / sqlfluff (test-fix)
     runs-on: ubuntu-latest
     strategy:
